from collections.abc import Callable
from typing import Type, TypedDict, TypeVar

import audio
from pygame.typing import FileLike
from typing_extensions import Buffer

def init() -> None: ...
def quit() -> None: ...
def get_sdl_mixer_version(linked: bool = True) -> tuple[int, int, int]: ...
def ms_to_frames(sample_rate: int, ms: int) -> int: ...
def frames_to_ms(sample_rate: int, frames: int) -> int: ...
def get_decoders() -> list[str]: ...

T = TypeVar("T")
track_stopped_callback = Callable[[T, Track], None]
track_mix_callback = Callable[[T, Track, audio.AudioSpec, Buffer], None]
group_mix_callback = Callable[[T, Group, audio.AudioSpec, Buffer], None]
post_mix_callback = Callable[[T, Mixer, audio.AudioSpec, Buffer], None]

class Mixer:
    def __init__(
        self,
        device: audio._AudioDevice = audio.DEFAULT_PLAYBACK_DEVICE,
        spec: audio.AudioSpec | None = None,
    ) -> None: ...
    @property
    def gain(self) -> float: ...
    @gain.setter
    def gain(self, value: float): ...
    def play_tag(self, tag: str, **kwargs) -> None: ...
    def stop_tag(self, tag: str, fade_out_ms: int = 0) -> None: ...
    def pause_tag(self, tag: str) -> None: ...
    def resume_tag(self, tag: str) -> None: ...
    def set_tag_gain(self, tag: str, gain: float) -> None: ...
    def play_audio(self, audio: Audio, /) -> None: ...
    def stop_all_tracks(self, fade_out_ms: int = 0) -> None: ...
    def pause_all_tracks(self) -> None: ...
    def resume_all_tracks(self) -> None: ...
    @property
    def format(self) -> audio.AudioSpec: ...
    def set_post_mix_callback(
        self, callback: post_mix_callback | None, userdata: T
    ) -> None: ...

class MemoryMixer(Mixer):
    def __init__(self, spec: audio.AudioSpec) -> None: ...
    def generate(self, buffer: Buffer, buflen: int) -> None: ...

class Audio:
    def __init__(
        self,
        file: FileLike,
        predecode: bool = False,
        preferred_mixer: Mixer | None = None,
    ) -> None: ...
    @classmethod
    def from_raw(cls, buf: Buffer) -> Audio: ...
    @classmethod
    def from_sine_wave(
        hz: int,
        amplitude: float,
        preferred_mixer: Mixer | None = None,
    ) -> Audio: ...
    @property
    def duration_frames(self) -> int | None: ...
    @property
    def duration_ms(self) -> int | None: ...
    @property
    def duration_infinite(self) -> bool: ...
    @property
    def format(self) -> audio.AudioSpec: ...
    def ms_to_frames(self, ms: int) -> int: ...
    def frames_to_ms(self, frames: int) -> int: ...
    def get_metadata() -> _MusicMetadataDict: ...

class Group:
    def __init__(self, mixer: Mixer) -> None: ...
    @property
    def mixer(self) -> Mixer: ...
    def set_post_mix_callback(
        self, callback: group_mix_callback | None, userdata: Type[T]
    ) -> None: ...

class Track:
    def __init__(self, mixer: Mixer) -> None: ...
    def set_audio(self, audio: Audio | None) -> None: ...
    def get_audio(self) -> Audio | None: ...
    def set_audiostream(self, audiostream: audio.AudioStream | None) -> None: ...
    def get_audiostream(self) -> audio.AudioStream | None: ...
    def set_filestream(self, file: FileLike) -> None: ...
    def play(
        self,
        loops: int = 0,
        max_frame: int = -1,
        max_ms: int = -1,
        start_frame: int = 0,
        start_ms: int = 0,
        loop_start_frame: int = 0,
        loop_start_ms: int = 0,
        fadein_frames: int = 0,
        fadein_ms: int = 0,
        append_silence_frames: int = 0,
        append_silence_ms: int = 0,
    ) -> None: ...
    @property
    def mixer(self) -> Mixer: ...
    def add_tag(self, tag: str) -> None: ...
    def remove_tag(self, tag: str) -> None: ...
    def set_group(self, group: Group | None) -> None: ...
    def set_playback_position(self, frames: int) -> None: ...
    def get_playback_position(self) -> int: ...
    def get_remaining_frames(self) -> int | None: ...
    def ms_to_frames(self, ms: int) -> int: ...
    def frames_to_ms(self, ms: int) -> int: ...
    def stop(self, fade_out_frames: int = 0) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    @property
    def playing(self) -> bool: ...
    @property
    def paused(self) -> bool: ...
    @property
    def looping(self) -> bool: ...
    @property
    def gain(self) -> float: ...
    @gain.setter
    def gain(self, value: float): ...
    @property
    def frequency_ratio(self) -> float: ...
    @frequency_ratio.setter
    def frequency_ratio(self, value: float): ...
    def set_output_channel_map(self, channel_map: list[int] | None) -> None: ...
    def set_stereo(self, left_gain: float, right_gain: float) -> None: ...
    def set_3d_position(self, position: tuple[float, float, float]) -> None: ...
    def get_3d_position(self) -> tuple[float, float, float]: ...
    def set_stopped_callback(
        self, callback: track_stopped_callback | None, userdata: T
    ) -> None: ...
    def set_raw_callback(
        self, callback: track_mix_callback | None, userdata: T
    ) -> None: ...

class AudioDecoder:
    def __init__(self, file: FileLike) -> None: ...
    @property
    def format(self) -> audio.AudioSpec: ...
    def decode(buffer: Buffer, spec: audio.AudioSpec) -> int: ...

class _MusicMetadataDict(TypedDict):
    title: str
    album: str
    artist: str
    copyright: str
