from collections.abc import Callable
from dataclasses import dataclass
from typing import TypeVar

from pygame.typing import FileLike
from typing_extensions import Buffer

def get_current_audio_driver() -> str: ...
def get_audio_drivers() -> list[str]: ...
def get_playback_devices() -> list[PhysicalAudioDevice]: ...
def get_recording_devices() -> list[PhysicalAudioDevice]: ...
def mix_audio(dst: Buffer, src: Buffer, format: AudioFormat, volume: float) -> None: ...
def load_wav(file: FileLike) -> tuple[AudioSpec, bytes]: ...
def convert_samples(
    src_spec: AudioSpec, src_data: Buffer, dst_spec: AudioSpec
) -> bytes: ...

DEFAULT_RECORDING_DEVICE: PhysicalAudioDevice
DEFAULT_PLAYBACK_DEVICE: PhysicalAudioDevice

T = TypeVar("T")
stream_callback = Callable[[T, AudioStream, int, int], None]
post_mix_callback = Callable[[T, AudioStream, Buffer], None]
iteration_callback = Callable[[T, _AudioDevice, bool], None]

class AudioFormat:
    def __init__(self, value: int) -> None: ...
    # So that PyLong_AsLong will get it as an integer
    def __index__(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def bitsize(self) -> int: ...
    @property
    def bytesize(self) -> int: ...
    @property
    def is_big_endian(self) -> bool: ...
    @property
    def is_float(self) -> bool: ...
    @property
    def is_int(self) -> bool: ...
    @property
    def is_little_endian(self) -> bool: ...
    @property
    def is_signed(self) -> bool: ...
    @property
    def is_unsigned(self) -> bool: ...
    @property
    def silence_value(self) -> int: ...

formats: list[AudioFormat]

U8: AudioFormat
S8: AudioFormat
S16LE: AudioFormat
S16BE: AudioFormat
S32LE: AudioFormat
S32BE: AudioFormat
F32LE: AudioFormat
F32BE: AudioFormat
S16: AudioFormat
S32: AudioFormat
F32: AudioFormat

@dataclass
class AudioSpec:
    format: AudioFormat
    channels: int
    freq: int

    @property
    def framesize(self) -> int: ...

class _AudioDevice:
    def open(self, spec: AudioSpec | None) -> LogicalAudioDevice: ...
    def open_stream(
        self, spec: AudioSpec | None, callback: stream_callback, userdata: T
    ) -> AudioStream: ...
    def bind(self, *args: AudioStream) -> None: ...
    def unbind(self, *args: AudioStream) -> None: ...
    @property
    def is_playback(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def paused(self) -> bool: ...
    def get_channel_map(self) -> list[int] | None: ...

class PhysicalAudioDevice(_AudioDevice):
    pass

class LogicalAudioDevice(_AudioDevice):
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    @property
    def gain(self) -> float: ...
    @gain.setter
    def gain(self, value: float): ...
    def set_iteration_callbacks(
        self,
        start: iteration_callback | None,
        end: iteration_callback | None,
        userdata: T,
    ) -> None: ...
    def set_post_mix_callback(
        self, callback: post_mix_callback | None, userdata: T
    ) -> None: ...

class AudioStream:
    def __init__(self, src_spec: AudioSpec, dst_spec: AudioSpec) -> None: ...
    def clear(self) -> None: ...
    def flush(self) -> None: ...
    def get_available_bytes(self) -> int: ...
    def get_queued_bytes(self) -> int: ...
    def get_data(self) -> bytes: ...
    def put_data(self, data: Buffer) -> None: ...

    # pause_device, resume_device, device_paused could all just be called on device?
    # .device.pause(), .device.resume
    def pause_device(self) -> None: ...
    def resume_device(self) -> None: ...
    @property
    def device_paused(self) -> bool: ...
    @property
    def device(self) -> _AudioDevice: ...
    @property
    def src_format(self) -> AudioSpec: ...
    @src_format.setter
    def src_format(self, value: AudioSpec) -> None: ...
    @property
    def dst_format(self) -> AudioSpec: ...
    @dst_format.setter
    def dst_format(self, value: AudioSpec) -> None: ...
    @property
    def gain(self) -> float: ...
    @gain.setter
    def gain(self, value: float): ...
    @property
    def frequency_ratio(self) -> float: ...
    @gain.setter
    def frequency_ratio(self, value: float): ...
    def set_input_channel_map(self, channel_map: list[int] | None) -> None: ...
    def get_input_channel_map(self) -> list[int] | None: ...
    def set_output_channel_map(self, channel_map: list[int] | None) -> None: ...
    def get_output_channel_map(self) -> list[int] | None: ...
    def lock(self) -> None: ...
    def unlock(self) -> None: ...
    def set_get_callback(
        self, callback: stream_callback | None, userdata: T
    ) -> None: ...
    def set_put_callback(
        self, callback: stream_callback | None, userdata: T
    ) -> None: ...
